title: Masterthesis Project 
author: Denise Bischof
email: denisebischof@web.de
description: WIP Scene collection from my master thesis project.

social:
  twitter: 
  facebook: 
  instagram: 
  github: denisebischof
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
